---
shared:
  image: python

jobs:
  main:
    steps:
      - install:
	- pip install -r requirements.txt
        - pip install coveralls
      - tests: nosetests tests --with-coverage --cover-package yact
      - post_tests:
        - coveralls
