---
shared:
  image: python

jobs:
  main:
    steps:
      - install-requirements: pip install -r requirements.txt
      - install-coveralls: pip install coveralls
      - tests: nosetests tests --with-coverage --cover-package yact
      - post_tests: coveralls
